/**
 * Cookie Manager Module
 * Import/Export cookies in multiple formats
 *
 * Supported formats:
 * - JSON (Playwright native)
 * - Netscape (cookies.txt)
 * - EditThisCookie (JSON array)
 * - Base64 encoded JSON
 */

const fs = require('fs');
const path = require('path');

/**
 * Export cookies to JSON format (Playwright native)
 * @param {Array} cookies - Playwright cookies array
 * @returns {string} JSON string
 */
function exportJSON(cookies) {
  return JSON.stringify(cookies, null, 2);
}

/**
 * Import cookies from JSON format
 * @param {string} jsonString - JSON string
 * @returns {Array} Playwright cookies array
 */
function importJSON(jsonString) {
  const cookies = JSON.parse(jsonString);

  // Validate and normalize
  return cookies.map(cookie => normalizeCookie(cookie));
}

/**
 * Export cookies to Netscape format (cookies.txt)
 * @param {Array} cookies - Playwright cookies array
 * @returns {string} Netscape format string
 */
function exportNetscape(cookies) {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# https://curl.se/docs/http-cookies.html',
    '# This file was generated by MMO Express',
    '',
  ];

  for (const cookie of cookies) {
    // Format: domain	flag	path	secure	expiry	name	value
    const domain = cookie.domain.startsWith('.') ? cookie.domain : `.${cookie.domain}`;
    const flag = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path = cookie.path || '/';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expiry = cookie.expires ? Math.floor(cookie.expires) : 0;
    const name = cookie.name;
    const value = cookie.value;

    lines.push(`${domain}\t${flag}\t${path}\t${secure}\t${expiry}\t${name}\t${value}`);
  }

  return lines.join('\n');
}

/**
 * Import cookies from Netscape format
 * @param {string} netscapeString - Netscape format string
 * @returns {Array} Playwright cookies array
 */
function importNetscape(netscapeString) {
  const cookies = [];
  const lines = netscapeString.split('\n');

  for (const line of lines) {
    // Skip comments and empty lines
    if (line.startsWith('#') || line.trim() === '') {
      continue;
    }

    const parts = line.split('\t');
    if (parts.length >= 7) {
      const [domain, , cookiePath, secure, expiry, name, value] = parts;

      cookies.push(normalizeCookie({
        name: name.trim(),
        value: value.trim(),
        domain: domain.trim().replace(/^\./, ''),
        path: cookiePath.trim() || '/',
        secure: secure.toUpperCase() === 'TRUE',
        expires: parseInt(expiry) || undefined,
        httpOnly: false,
        sameSite: 'Lax',
      }));
    }
  }

  return cookies;
}

/**
 * Export cookies to EditThisCookie format
 * @param {Array} cookies - Playwright cookies array
 * @returns {string} EditThisCookie JSON string
 */
function exportEditThisCookie(cookies) {
  const etcCookies = cookies.map(cookie => ({
    domain: cookie.domain,
    expirationDate: cookie.expires,
    hostOnly: !cookie.domain.startsWith('.'),
    httpOnly: cookie.httpOnly || false,
    name: cookie.name,
    path: cookie.path || '/',
    sameSite: cookie.sameSite || 'unspecified',
    secure: cookie.secure || false,
    session: !cookie.expires,
    storeId: '0',
    value: cookie.value,
  }));

  return JSON.stringify(etcCookies, null, 2);
}

/**
 * Import cookies from EditThisCookie format
 * @param {string} etcString - EditThisCookie JSON string
 * @returns {Array} Playwright cookies array
 */
function importEditThisCookie(etcString) {
  const etcCookies = JSON.parse(etcString);

  return etcCookies.map(cookie => normalizeCookie({
    name: cookie.name,
    value: cookie.value,
    domain: cookie.domain,
    path: cookie.path || '/',
    secure: cookie.secure || false,
    httpOnly: cookie.httpOnly || false,
    expires: cookie.expirationDate,
    sameSite: normalizeSameSite(cookie.sameSite),
  }));
}

/**
 * Export cookies to Base64 encoded JSON
 * @param {Array} cookies - Playwright cookies array
 * @returns {string} Base64 string
 */
function exportBase64(cookies) {
  const json = JSON.stringify(cookies);
  return Buffer.from(json).toString('base64');
}

/**
 * Import cookies from Base64 encoded JSON
 * @param {string} base64String - Base64 string
 * @returns {Array} Playwright cookies array
 */
function importBase64(base64String) {
  const json = Buffer.from(base64String, 'base64').toString('utf8');
  return importJSON(json);
}

/**
 * Detect cookie format from string
 * @param {string} cookieString - Cookie string
 * @returns {string} Format: 'json', 'netscape', 'editthiscookie', 'base64', 'unknown'
 */
function detectFormat(cookieString) {
  const trimmed = cookieString.trim();

  // Check for Netscape format
  if (trimmed.startsWith('# Netscape') || trimmed.startsWith('# HTTP Cookie')) {
    return 'netscape';
  }

  // Check for base64
  if (/^[A-Za-z0-9+/=]+$/.test(trimmed) && trimmed.length > 50) {
    try {
      const decoded = Buffer.from(trimmed, 'base64').toString('utf8');
      JSON.parse(decoded);
      return 'base64';
    } catch {
      // Not valid base64 JSON
    }
  }

  // Check for JSON
  if (trimmed.startsWith('[') || trimmed.startsWith('{')) {
    try {
      const parsed = JSON.parse(trimmed);

      // Check if it's EditThisCookie format (has storeId, hostOnly)
      if (Array.isArray(parsed) && parsed.length > 0) {
        if ('storeId' in parsed[0] || 'hostOnly' in parsed[0]) {
          return 'editthiscookie';
        }
        return 'json';
      }
      return 'json';
    } catch {
      // Not valid JSON
    }
  }

  // Check for tab-separated (Netscape without header)
  if (trimmed.includes('\t')) {
    const firstLine = trimmed.split('\n')[0];
    if (firstLine.split('\t').length >= 7) {
      return 'netscape';
    }
  }

  return 'unknown';
}

/**
 * Auto-import cookies from any supported format
 * @param {string} cookieString - Cookie string in any format
 * @returns {Array} Playwright cookies array
 */
function autoImport(cookieString) {
  const format = detectFormat(cookieString);

  switch (format) {
    case 'json':
      return importJSON(cookieString);
    case 'netscape':
      return importNetscape(cookieString);
    case 'editthiscookie':
      return importEditThisCookie(cookieString);
    case 'base64':
      return importBase64(cookieString);
    default:
      throw new Error(`Unknown cookie format. Supported: JSON, Netscape, EditThisCookie, Base64`);
  }
}

/**
 * Save cookies to file
 * @param {Array} cookies - Cookies array
 * @param {string} filePath - File path
 * @param {string} format - Export format
 */
function saveToFile(cookies, filePath, format = 'json') {
  let content;

  switch (format) {
    case 'netscape':
      content = exportNetscape(cookies);
      break;
    case 'editthiscookie':
      content = exportEditThisCookie(cookies);
      break;
    case 'base64':
      content = exportBase64(cookies);
      break;
    default:
      content = exportJSON(cookies);
  }

  fs.writeFileSync(filePath, content, 'utf8');
  return filePath;
}

/**
 * Load cookies from file
 * @param {string} filePath - File path
 * @returns {Array} Playwright cookies array
 */
function loadFromFile(filePath) {
  if (!fs.existsSync(filePath)) {
    throw new Error(`Cookie file not found: ${filePath}`);
  }

  const content = fs.readFileSync(filePath, 'utf8');
  return autoImport(content);
}

/**
 * Normalize cookie to Playwright format
 * @param {Object} cookie - Cookie object
 * @returns {Object} Normalized cookie
 */
function normalizeCookie(cookie) {
  const normalized = {
    name: cookie.name,
    value: cookie.value,
    domain: cookie.domain,
    path: cookie.path || '/',
  };

  // Handle secure
  if (cookie.secure !== undefined) {
    normalized.secure = Boolean(cookie.secure);
  }

  // Handle httpOnly
  if (cookie.httpOnly !== undefined) {
    normalized.httpOnly = Boolean(cookie.httpOnly);
  }

  // Handle expires
  if (cookie.expires && cookie.expires > 0) {
    // Convert to seconds if it's in milliseconds
    normalized.expires = cookie.expires > 9999999999
      ? cookie.expires / 1000
      : cookie.expires;
  }

  // Handle sameSite
  if (cookie.sameSite) {
    normalized.sameSite = normalizeSameSite(cookie.sameSite);
  }

  return normalized;
}

/**
 * Normalize sameSite value
 * @param {string} sameSite - SameSite value
 * @returns {string} Normalized value
 */
function normalizeSameSite(sameSite) {
  if (!sameSite || sameSite === 'unspecified' || sameSite === 'no_restriction') {
    return 'None';
  }
  const lower = sameSite.toLowerCase();
  if (lower === 'lax') return 'Lax';
  if (lower === 'strict') return 'Strict';
  if (lower === 'none') return 'None';
  return 'Lax';
}

/**
 * Filter cookies by domain
 * @param {Array} cookies - Cookies array
 * @param {string} domain - Domain to filter
 * @returns {Array} Filtered cookies
 */
function filterByDomain(cookies, domain) {
  const normalizedDomain = domain.toLowerCase().replace(/^\./, '');
  return cookies.filter(cookie => {
    const cookieDomain = cookie.domain.toLowerCase().replace(/^\./, '');
    return cookieDomain === normalizedDomain || normalizedDomain.endsWith(`.${cookieDomain}`);
  });
}

/**
 * Merge cookies (newer values override older)
 * @param {Array} existing - Existing cookies
 * @param {Array} newCookies - New cookies to merge
 * @returns {Array} Merged cookies
 */
function mergeCookies(existing, newCookies) {
  const cookieMap = new Map();

  // Add existing cookies
  for (const cookie of existing) {
    const key = `${cookie.domain}|${cookie.path}|${cookie.name}`;
    cookieMap.set(key, cookie);
  }

  // Override with new cookies
  for (const cookie of newCookies) {
    const key = `${cookie.domain}|${cookie.path}|${cookie.name}`;
    cookieMap.set(key, cookie);
  }

  return Array.from(cookieMap.values());
}

module.exports = {
  // Export functions
  exportJSON,
  exportNetscape,
  exportEditThisCookie,
  exportBase64,

  // Import functions
  importJSON,
  importNetscape,
  importEditThisCookie,
  importBase64,
  autoImport,

  // File operations
  saveToFile,
  loadFromFile,

  // Utilities
  detectFormat,
  normalizeCookie,
  filterByDomain,
  mergeCookies,
};
